const CLEAR_CART = 'CLEAR_CART'
const REMOVE_ITEM = 'REMOVE_ITEM'
const INCREASE_COUNT = 'INCREASE_COUNT'
const DECREASE_COUNT = 'DECREASE_COUNT'
const LOADING = 'LOADING'
const DISPLAY_ITEMS = 'DISPLAY_ITEMS'

export { CLEAR_CART, REMOVE_ITEM, INCREASE_COUNT, DECREASE_COUNT, LOADING, DISPLAY_ITEMS }
