const CLEAR_CART = 'CLEAR_CART'
const REMOVE_ITEM = 'REMOVE_ITEM'
const INCREASE_COUNT = 'INCREASE_COUNT'
const DECREASE_COUNT = 'DECREASE_COUNT'

export { CLEAR_CART, REMOVE_ITEM, INCREASE_COUNT, DECREASE_COUNT }
